site_name: Koodous Documentation
favicon: favicon.png
pages:
- ['index.md', 'Home']

- ['rest-api/getting-started.md','REST API', 'Getting started']
- ['rest-api/apks.md','REST API', 'APKs']

- ['yara/getting-started.md','Yara', 'Getting started']