site_name: Koodous Documentation
site_favicon: favicon.png
google_analytics: ['UA-62062848-2', 'docs.koodous.com']
strict: true
theme: readthedocs
pages:
- Home: 'index.md'

- The Koodous web:
  - Getting started: 'web/getting-started.md'
  - The repository: 'web/the-repo.md'
  # - Dashboard: 'web/dashboard.md'
  # - Community Rulesets: 'web/community_rulesets.md'
  # - Your Rulesets: 'web/your_rulesets.md'
  # - APKs: 'web/apks.md'
  # - Notifications: 'web/notifications.md'

- REST API:
  - Getting started: 'rest-api/getting-started.md'

- REST API (most used methods):
  - APKs: 'rest-api/apks.md'
  - APK Download: 'rest-api/apk-download.md'
  - APK Upload: 'rest-api/apk-upload.md'
  - APK Analysis: 'rest-api/apk-analysis.md'
  - APKs feed: 'feed/apks.md'
  - Analyses feed: 'feed/analyses.md'
  - Detected feed: 'feed/detected.md'

- REST API (misc methods):
  - APK Comments: 'rest-api/apk-comments.md'
  - APK Votes: 'rest-api/apk-votes.md'
  - Analysts: 'rest-api/analysts.md'
  - Your Rulesets: 'rest-api/user_rulesets.md'
  - Public Rulesets: 'rest-api/public_rulesets.md'
  - Public Rulesets Votes: 'rest-api/public_rulesets_votes.md'
  - Public Rulesets Comments: 'rest-api/public_rulesets_comments.md'

- Yara:
  - Getting started: 'yara/getting-started.md'
  - Androguard: 'yara/androguard.md'
  - Droidbox: 'yara/droidbox.md'
  - File: 'yara/file.md'
