site_name: Koodous Documentation
site_favicon: favicon.png
google_analytics: ['UA-62062848-2', 'docs.koodous.com']
strict: true
theme: readthedocs
pages:
- ['index.md', 'Home']
- ['web/getting-started.md','The Koodous web', 'Getting started']
- ['web/the-repo.md','The Koodous web', 'The repository']
- ['rest-api/getting-started.md','REST API', 'Getting started']
- ['rest-api/apks.md','REST API', 'APKs']
- ['rest-api/apk-comments.md','REST API', 'APK Comments']
- ['rest-api/analysts.md','REST API', 'Analysts']
- ['rest-api/rulesets.md','REST API', 'Rulesets']
- ['yara/getting-started.md','Yara', 'Getting started']
- ['yara/androguard.md','Yara', 'Androguard']
- ['yara/droidbox.md','Yara', 'Droidbox']

