name: GH pages deploy

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - name: Setup python
      uses: actions/setup-python@v1
    - run: |
        pip install -r requirements
        mkdocs gh-deploy
